### ISSUE TITLE
Todo before v1 release

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#606]
TODO

- [x] code linting
- [x] menu/dropdown/switch: unify `values` parsing
- [x] meta infos in session files 
- [ ] example sessions
- [x] scripting documentation
- [x] general documentation
- [x] missing properties descriptions
- [x] sliders design choices names
- [x] improve property help modal
- [ ] pasted widget position is not always predictable (optional)
- [ ] editor keyboard shortcuts (a more natural tree navigation) (optional)

**Comment by avenantsoftware** [comment]
How about http://materialdesignicons.com icon support next to fontawesome support? all their icons are free and they have much more icons like midi and note icons etc...

How about an option to hide the upper bar with the 3 menu dots?

**Comment by jean-emmanuel** [comment]
I'll check this alternative out, however I'm not in favor of keeping 2 different icon fonts.

> How about an option to hide the upper bar with the 3 menu dots?

> How about an option to hide the upper bar with the 3 menu dots?

There's no upper bar so to speak, it's a tab which you can remove if you want. The menu button can be hidden with a custom theme.

**Comment by mikerodd** [comment]
A mini thing to do : the .deb  package of the last alpha indicates a proprietary licence, I guess it's not intended ;-)

**Comment by jean-emmanuel** [comment]
@mikerodd ->https://github.com/jean-emmanuel/open-stage-control/issues/615

**Comment by mxklb** [comment]
Which Ports are used by the node version? 

Sorry but I can't find information about used Ports in docs .. thank you :1st_place_medal:

**Comment by jean-emmanuel** [comment]
The default http port is 8080. The osc input ports is the same as the http port by default.

**Comment by mxklb** [comment]
ah, so no other ports involved for sending osc, all right, thank you & sorry i'm new to osc ..

**Comment by nlebellier** [comment]
examples would be great. Your documentation is very good but sometimes short examples doing basic stuff would be very appreciated to start with o-s-c. Maybe a forum category : concepts for newbies ?

**Comment by jean-emmanuel** [comment]
Examples are not ready yet but I'm releasing v1 now because it looks stable enough and there no reason to hold it any longer.
